---
region_suffix: lgb
int_dns_primary: "{{ vault_lgb_ad_ip }}"
int_dns_secondary: "{{ vault_lgb_pihole_ip }}"
pxe_server_ip: "{{ vault_lgb_pxe_ip }}"
pxe_server_delegation: "nas-{{ region_suffix }}.{{ vault_internal_host_dns }}"
snmp_location: Long Beach, CA
timezone: America/Los_Angeles
win_deploy_timezone: "Pacific Standard Time"
internal_dns_controller: "dc-lgb.ad.kittytel.net"
#rocky_linux_mirror: "http://repocache.kittytel.net/rocky"
rocky_linux_mirror: "https://rocky-linux-us-west1.production.gcp.mirrors.ctrliq.cloud/pub/rocky/"
vm_pool_directory: default
default_vm_bridge: adbr0
vm_local_bridge: adbr0
#vm_domain_bridge: adbr0
vm_default_hypervisor: hv-lgb.ad.kittytel.net
vm_use_efi: true
vm_console_log_enabled: false
vm_autostart: false
ip_use_dhcp: true
vm_internal: yes
ks_use_disk: vda
become: yes
