---
vm_hypervisor: hv-lgb.ad.kittytel.net
vm_libvirt_vm_engine: kvm
vm_libvirt_vm_arch: x86_64
vm_enable_spice: yes

default_vm_bridge: "{{ vlans[default_vlan].bridge }}"

libvirt_vm_default_console_log_dir: "/var/log/libvirt-consoles/"
libvirt_vm_default_uuid_deterministic: False
libvirt_volume_default_images_path: '/var/lib/libvirt/images'

libvirt_volume_default_file_name: "{{ vm_name }}-disk"
libvirt_volume_default_type: file
libvirt_volume_default_format: qcow2
libvirt_volume_default_device: disk
libvirt_vm_image_cache_path: "{{ libvirt_image_cache_path }}"
libvirt_vm_arch: x86_64
libvirt_vm_clock_offset: False
libvirt_vm_trust_guest_rx_filters: false
libvirt_vm_virsh_default_env: "{{  { 'LIBVIRT_DEFAULT_URI': libvirt_vm_uri } if libvirt_vm_uri else {} }}"
libvirt_vm_uri: ""
libvirt_vm_sudo: true
libvirt_cpu_mode_default: "{{ 'host-passthrough' if libvirt_vm_engine == 'kvm' else 'host-model' }}"
libvirt_image_cache_path: "/tmp/"
vm_new_random_mac: "{{ '52:54:00' | random_mac }}"
vm_cpu_mode: host-model
vm_machine: q35
vm_use_tpm: false
vm_libvirt_vm_emulator: /usr/bin/qemu-system-x86_64


