---
- name: "Build WinPE based WinSelect ISO for PXE"
  hosts: winbox.ad.kittytel.net
  vars:
    virtio_version: "0.1.248"
    build_arch:
#      - amd64
      - arm64
    target_copy_smb: "nas-lgb.ad.kittytel.net"
    vmware_tools_version: "13.0.0-24696409"
  roles:
  - msvc-toolchain
  tasks:
  - name: "Build WinSelect for {{ build_arch }}"
    include_tasks: tasks/build-winselect.yaml
    loop: "{{ build_arch }}"
    loop_control:
      loop_var: build_target_arch
