---
- name: Provision LGB NAS server (Lil NAS X)
  hosts: nas-lgb.ad.kittytel.net
  become: yes
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
  roles:
    - monitoring-internal
    - shell-niceties
    - ad-member
    - smart-monitoring
    - server-smb
    - server-smb-legacy
    - server-afp
    - server-nfs
    - server-pxe
  tasks: 
  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/postflight/ssh-keys.yaml  
    - name: Standard post-flight tasks
      import_tasks: tasks/postflight/main.yaml