---
- name: Provision RHEL shell
  hosts: rhelshell.ad.kittytel.net
  become: yes
  remote_user: "{{ vault_ansible_deployment_user }}"
  become_method: sudo
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
    - name: Ensure /etc/ansible directory exists
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Mount NFS share
      ansible.builtin.mount:
        path: /etc/ansible
        src: nas-lgb.ad.kittytel.net:/nas/ansible
        fstype: nfs
        opts: rw,sync,noatime,nodiratime,rsize=1048576,wsize=1048576,hard,intr,vers=4.2
        state: mounted
  roles:
    - monitoring-internal
    - shell-niceties
    - secure-ssh
    - ad-member
    - argo-cd-cli
  tasks:
    - name: Configure Kubernetes repository
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/repodata/repomd.xml.key
        state: present
    - name: Install required RPM packages
      package: 
        name: 
          - ansible-core
          - ansible-collection-community-general
          - ansible-collection-ansible-posix
          - ansible-test
          - epel-release
          - gcc
          - krb5-devel
          - kubectl
          - make
          - nfs-utils
          - openssl
          - python3-devel
          - python3-firewall
          - python3-gssapi
          - python3-krb5
          - python3-pip
          - python3-requests-kerberos
          - python3-winrm
        state: present
    - name: "PIP install pywinrm[kerberos]"
      ansible.builtin.pip:
        name: "pywinrm[kerberos]"
        executable: pip3
    - name: Import OpenBao RPM GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://github.com/openbao/openbao/releases/download/v2.4.1/bao_2.4.1_linux_amd64.rpm.gpgsig
    - name: Install OpenBao RPM package
      ansible.builtin.yum:
        name: https://github.com/openbao/openbao/releases/download/v2.4.1/bao_2.4.1_linux_amd64.rpm
        state: present
  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/postflight/ssh-keys.yaml  
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root