- name: "Host-Based Playbook for secret.ad.kittytel.net"
  hosts: "secret.ad.kittytel.net"
  ignore_unreachable: true
  become: true
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
  roles:
  - monitoring-internal
  - shell-niceties
  - secure-ssh
  - openbao-pki
  tasks:

  post_tasks:
    - name: Standard post-flight tasks
      import_tasks: tasks/postflight/main.yaml
