---
- name: Provision LGB NAS server (Lil NAS X)
  hosts: nas-lgb.ad.kittytel.net
  become: yes
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
  roles:
    - monitoring-internal
    - shell-niceties
    - ad-member
    - server-smb
    - server-smb-legacy
    - server-afp
    - server-nfs
    - server-pxe
  tasks:
    - name: Install smartmontools and snmp configuration
      import_tasks: tasks/postflight/snmp-smart.yaml 

    - name: restart snmpd
      service:
        name: snmpd
        state: restarted
        enabled: yes        
  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/postflight/ssh-keys.yaml  
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root