---
- name: Provision LGB hypervisor
  hosts: hv-lgb.ad.kittytel.net
  become: yes
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
  roles:
    - monitoring-internal
    - hardware-sensors
    - smart-monitoring
    - shell-niceties
    - hypervisor
    - lilnas-hv
  tasks:
  post_tasks:
    - name: Install SSH authorized keys
      import_tasks: tasks/postflight/ssh-keys.yaml  
    - name: Standard post-flight tasks
      import_tasks: tasks/postflight/main.yaml