---
- name: Provision LGB hypervisor
  hosts: hv-lgb.ad.kittytel.net
  become: yes
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
  roles:
    - monitoring-internal
    - hardware-sensors
    - shell-niceties
    - hypervisor
    - lilnas-hv
  tasks:
    - name: Install smartmontools and snmp configuration
      import_tasks: tasks/postflight/snmp-smart.yaml  
  post_tasks:
    - name: Install SSH authorized keys
      import_tasks: tasks/postflight/ssh-keys.yaml  
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root