---
- name: Containerized KittyTel Services beta
  hosts: k3s_test_lgb
  remote_user: "{{ vault_ansible_deployment_user }}"
  become: yes
  become_method: sudo
  ignore_unreachable: true
  pre_tasks:
    - name: Standard pre-flight tasks
      import_tasks: tasks/preflight/main.yaml
      ignore_unreachable: true
  roles:
    - shell-niceties
    - monitoring-internal
    - ad-member
    - k3s-single-node
  tasks:
    - name: Setup MetalLB address pool
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/metallb.yaml'
        wait: true
    - name: Setup local retained storage class
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/local-storage-retained.yaml'
        wait: true
    - name: Setup nfs storage class
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/nfs.yaml'
        wait: true

    - name: Setup cert-manager config
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/cert-manager.yaml.j2'
    #- name: Setup pihole/unbound
    #  kubernetes.core.k8s:
    #    state: present
     #   template: 'k3s-services/dnsfilter.yaml'
    #- name: Setup unifi
    #  kubernetes.core.k8s:
    #    state: present
    #    template: 'k3s-services/unifi.yaml'
    - name: Setup kms
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/kms.yaml'
    - name: Setup jellyfin
      kubernetes.core.k8s:
        state: present
        template: 'k3s-services/jellyfin.yaml'

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
