---
- name: Provision PXE Server Playbook
  hosts: pxe-lgb.ad.kittytel.net
  remote_user: '{{ vault_ansible_deployment_user }}'
  become: yes
  become_method: sudo

  # The following pre-task ansible check is
  # borrowed from Rocky Linux ansible playbooks
  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible
    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"
    - name: Deploy failsafe user account
      import_tasks: tasks/provisioning/failsafe.yml
    - name: Deploy kitty telecom root CA
      import_tasks: tasks/provisioning/root-ca.yml
    - name: Set Hostname
      hostname: 
        name: "{{ inventory_hostname }}"
    - name: Install base dependencies
      package: 
        name: 
          - python3-firewall
          - nfs-common
        state: present
    - name: mount PXE NAS
      mount:
        src: nas-lgb:/nas/osboot
        path: /srv
        opts: rw,sync,hard,noatime
        state: mounted
        fstype: nfs4
  roles:
    - monitoring-internal
    - shell-niceties
    - secure-ssh
    - role: server-pxe
      vars:
        pxe_distro:
          #- alpine-stable
          - debian-stable
          - rocky-stable
          - windows
  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/provisioning/cat-ssh.yml  
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root