---
- name: Provision snorlax
  hosts: snorlax.originull.org
  become: yes
  remote_user: "{{ vault_ansible_deployment_user }}"
  become_method: sudo

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible
    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"
    - name: Deploy failsafe user account
      import_tasks: tasks/provisioning/failsafe.yml
    - name: Deploy kitty telecom root CA
      import_tasks: tasks/provisioning/root-ca.yml
    - name: Set Hostname
      hostname: 
        name: "{{ inventory_hostname }}"
    - name: create user cat
      ansible.builtin.user:
        name: cat
        create_home: yes
    - name: add cat to sudo
      become: true
      copy:
        dest: /etc/sudoers.d/cat
        content: 'cat ALL=(ALL) NOPASSWD:ALL'
  roles:
    - monitoring-internal
    - shell-niceties

  tasks:
    - name: Deploy ACME certificates
      import_tasks: tasks/ssl/snorlax.yml
    - name: create user apturbo
      ansible.builtin.user:
        name: apturbo
        create_home: yes
        home: /var/www/aports-turbo/
    - name: create user gpt
      ansible.builtin.user:
        name: gpt
        create_home: yes
        home: /srv/gpt/
    - name: Install nginx
      package: 
        name: 
          - nginx
        state: present
  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/provisioning/cat-ssh.yml  
    - name: ensure nginx is enabled
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root