---
# Lets Encrypt SSL renewal
- name: SSL Certificate Renewal (svc-lgb)
  hosts: svc-lgb.ad.kittytel.net
  become: yes
  remote_user: "{{ vault_ansible_deployment_user }}"
  tasks:
    - name: Deploy ACME certificates for svc-lgb
      import_tasks: tasks/ssl/svc-lgb.yml

    - name: Set fact for SSL change on svc
      set_fact:
        svc_changed: true
      when: acme_challenge_your_domain['challenge_data'] is defined

    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
      when: svc_changed is defined
