---
- name: PXE Boot System
  hosts: pxe_boot
  remote_user: '{{ vault_ansible_deployment_user }}'
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
  - name: assert limit
    run_once: yes
    assert:
      that:
      - 'ansible_limit is defined'
      fail_msg: Playbook must be run with a limit (set a hostname to boot)
      quiet: yes
  roles:
  - pxe-autoinstall-client
  post_tasks:
  - name: Pause 240 seconds for system to boot from network
    pause:
      seconds: 240
    delegate_to: localhost
    become: no
  - name: Cleanup PXE
    include_tasks: tasks/preflight/vm/pxe-cleanup.yaml
