---
# Playbook to install Postfix, ClamAV, OpenDKIM, OpenDMARC, SpamAssassin

- name: "Generate an ID for the selector"
  shell:
    cmd: "date +%Y%m%d"
  register: new_selector_id

- name: "Run opendkim-geknkey for {{ new_selector_id.stdout_lines | join('') }}._domainkey.{{ dkim_dns_name }}"
  shell:
    cmd: "opendkim-genkey -b 2048 -d {{ dkim_dns_name }} -D /etc/opendkim/keys/{{ dkim_dns_name }} -s {{ new_selector_id.stdout }} -v"

- name: "Correct permissions on OpenDKIM keys"
  shell:
    cmd: "chown opendkim:opendkim /etc/opendkim/keys/{{ dkim_dns_name }}/*"

- name: "get DKIM public record for {{ dkim_dns_name }}" 
  shell:
    cmd: grep -Po "(?<=\")(.+)(?=\")" /etc/opendkim/keys/{{ dkim_dns_name }}/{{ new_selector_id.stdout_lines | join('') }}.txt  | sed -z 's/\n//g;'
  register: dkim_dns_value

- name: "create DKIM record for {{ new_selector_id.stdout_lines | join('') }}._domainkey.{{ dkim_dns_name }}" 
  cloudflare_dns:
    domain: "{{ dkim_dns_name }}"
    record: "{{ new_selector_id.stdout_lines | join('') }}._domainkey.{{ dkim_dns_name }}"
    type: TXT
    value: "{{ dkim_dns_value.stdout_lines | join('') | replace('\" \"', '') }}"
    state: present
    solo: true
    account_email: "{{ vault_cloudflare_email }}"
    account_api_token: "{{ vault_cloudflare_api_key }}"

- name: "Update signing.table"
  lineinfile:
    path: /etc/opendkim/signing.table
    line: "*@{{ dkim_dns_name }} {{ new_selector_id.stdout_lines | join('') }}._domainkey.{{ dkim_dns_name }}"

- name: "Update key.table"
  lineinfile:
    path: /etc/opendkim/key.table
    line: "{{ new_selector_id.stdout_lines | join('') }}._domainkey.{{ dkim_dns_name }} {{ dkim_dns_name }}:{{ new_selector_id.stdout_lines | join('') }}:/etc/opendkim/keys/{{ dkim_dns_name }}/{{ new_selector_id.stdout_lines | join('') }}.private"
