---
- name: "Add group {{ fpm_name }}"
  group: 
    name: "{{ fpm_name }}"
- name: "Add user {{ fpm_name }}"
  user:
    name: "{{ fpm_name }}"
    group: "{{ fpm_name }}"
    home: "/var/www/{{ fpm_name }}/"
    create_home: no
    comment: "{{ fpm_name }} operations"
    system: yes

- name: "correct {{ fpm_name }} permissions"
  file:
    path: "/var/www/{{ fpm_name }}/"
    state: directory
    recurse: yes
    owner: "{{ fpm_name }}"
    group: "{{ fpm_name }}"

- name: "install php-fpm configuration for {{ fpm_name }}"
  template:
    src: provisioning/php-fpm.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ fpm_name }}.conf"
    mode: '0644'
    owner: root
    group: root