---
## Playbook to deploy LibreNMS

- name: create php-fpm user for librenms
  import_tasks: tasks/provisioning/fpmuser.yml
  vars:
    fpm_name: librenms
    php_version: "8.2"

- name: Install requirements
  package:
    name: 
      - acl
      - curl
      - fping
      - git
      - graphviz
      - snmp
      - snmpd
      - whois
      - unzip
      - rrdtool
      - imagemagick
      - mtr-tiny
      - nmap
      - python3-pymysql
      - python3-dotenv
      - python3-redis
      - python3-setuptools
      - python3-systemd
      - python3-pip
    state: present

- name: check out librenms
  become_user: librenms
  git: 
    repo: https://github.com/librenms/librenms.git
    dest: /var/www/librenms/
    version: master
    force: true


- name: Install nginx configuration for librenms
  template:
    src: provisioning/nginx-librenms.conf.j2
    dest: "/etc/nginx/sites-available/librenms.conf"
    mode: '0644'
    owner: root
    group: root

- name: Fix our php open-basedir
  lineinfile:
    path: /etc/php/8.2/fpm/pool.d/librenms.conf
    regexp: '^php_admin_value\[open_basedir'
    line: php_admin_value[open_basedir] = /var/www/librenms/:/nms-data:/tmp:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

- name: Fix our php PATH
  lineinfile:
    path: /etc/php/8.2/fpm/pool.d/librenms.conf
    line: env[PATH] = /usr/local/bin:/usr/bin:/bin

- name: Fix our php timezone
  lineinfile:
    path: /etc/php/8.2/fpm/pool.d/librenms.conf
    line: php_admin_value[date.timezone] = America/Los_Angeles

# errors ignored as we will fix via our own .env
- name: install librenms composer dependencies
  command: 
    cmd: php8.2 /var/www/librenms/scripts/composer_wrapper.php install --no-dev
    chdir: /var/www/librenms/
  become_user: librenms
  ignore_errors: true

- name: Install librenms cron
  template:
    src: provisioning/librenms.cron.j2
    dest: "/etc/cron.d/librenms"
    mode: '0644'
    owner: root
    group: root

- name: install librenms log rotation
  copy:
    src: /var/www/librenms/misc/librenms.logrotate 
    dest: /etc/logrotate.d/librenms
    remote_src: true

- name: Install librenms config.php
  template:
    src: provisioning/librenms.config.php.j2
    dest: "/var/www/librenms/config.php"
    mode: '0644'
    owner: librenms
    group: librenms

- name: Install librenms env file
  template:
    src: provisioning/librenms.env.j2
    dest: "/var/www/librenms/.env"
    mode: '0640'
    owner: librenms
    group: librenms
