---
# Playbook to install Kitty Telecom Root CA

- name: Make sure the folder exists
  file:
    path: /usr/local/share/ca-certificates
    state: directory
  when: ansible_os_family == "Debian"

- name: Copy the certificate
  copy:
    src: files/root-ca.crt
    dest: /usr/local/share/ca-certificates/kittytel-root.crt
  register: result
  when: ansible_os_family == "Debian"

- name: Update CA Trust
  command: update-ca-certificates
  when: result is changed