---
- name: Add group "kitsnotes"
  group: 
    name: kitsnotes
- name: Add user "kitsnotes"
  user:
    name: kitsnotes
    group: kitsnotes
    home: /var/www/kitsnotes/
    create_home: no
    comment: "kitsnotes.com user"
    system: yes

- name: Copy php-fpm configuration
  template: 
    src: provisioning/php-kn.conf.j2
    dest: /etc/php-fpm.d/kitsnotes.conf
    mode: "0644"
  notify: restart php-fpm

- name: create kitsnotes folder
  file:
    path: /var/www/kitsnotes/
    state: directory
    mode: '0755'
    owner: kitsnotes
    group: kitsnotes