---

- name: "Deploy Lets Encrypt for {{ wf_proxy_domain }}"
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: "{{ wf_proxy_domain }}"
    requested_letsencrypt_domain: "{{ wf_proxy_domain }}"
    requested_letsencrypt_san_list:
      - "www.{{ wf_proxy_domain }}"

- name: "Copy NGINX proxy template for {{ wf_proxy_domain }}"
  template:
    src: provisioning/wf-nginx.conf.j2
    dest: "/etc/nginx/conf.d/proxy-{{ wf_proxy_domain }}.conf"
    mode: '0644'
    owner: root
    group: root