---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-hdd-retained
provisioner: nfs.csi.k8s.io
parameters:
  server: nas-lgb
  share: /nas/k3s_prod_pvs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer


