---
# Pre-tasks for creating PXE enabled VM
- name: "Check if /etc/ansible/host_vars/{{ inventory_hostname_short }}.{{ vault_internal_host_dns }} exists"
  stat:
    path: "/etc/ansible/host_vars/{{ inventory_hostname_short }}.{{ vault_internal_host_dns }}"
  delegate_to: localhost
  become: no
- name: Check Hypervisor for existing VM
  virt:
    command: list_vms
  delegate_to: "{{ vm_hypervisor }}"
  register: vm_list
- name: Check for VM and set vm_exists fact (noexist)
  set_fact:
    vm_exists: false
  when: vm_name not in vm_list.list_vms
- name: Check for VM and set vm_exists fact (exists)
  set_fact:
    vm_exists: true
  when: vm_name in vm_list.list_vms
- name: "Set DNS suffix host fact"
  set_fact:
    dns_suffix: "{{ vault_internal_host_dns }}"
- name: Ensure ks_use_disk fact is defined
  set_fact:
    sys_mac_addr: "vda"
  when: ks_use_disk is not defined
- name: Ensure sys_mac_addr fact is defined
  set_fact:
    sys_mac_addr: "{{ '52:54:00' | random_mac }}"
  when: sys_mac_addr is not defined
- name: Ensure vm_interfaces is defined
  set_fact:
    vm_interfaces:
    - type: 'bridge'
      mac: "{{ sys_mac_addr }}"
      source:
        dev: "{{ vm_local_bridge | default(default_vm_bridge) }}"
  when: vm_interfaces is not defined
- name: "Set MAC Address Fact (Defined)"
  set_fact:
      pxe_mac_address: "{{ sys_mac_addr }}"
  when: "sys_mac_addr is defined"