---
# Playbook to install SSHD security

- name: Copy SSH configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    owner: root
    group: root

- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes