---
- name: Add MariaDB RPM Repo
  template: 
    src: mariadb.repo.j2 
    dest: /etc/yum.repos.d/mariadb.repo
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == "RedHat"

- name: Install MariaDB Package
  become: yes
  package:
    name: MariaDB-server
    state: present
    
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
