---
# Playbook to install shell niceties

- name: Install Extra Packages for Enterprise Linux
  package: 
    name: 
      - epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install packages for shell niceties
  package: 
    name: 
      - nano
      - screen
    state: present

- name: Install packages for debian dynamic motd
  package: 
    name: 
      - fortunes
      - lolcat
      - cowsay
      - figlet
    state: present
  when: ansible_os_family == "Debian"

- name: Copy screenrc
  template:
    src: screenrc.j2
    dest: /etc/screenrc
    mode: '0644'
    owner: root
    group: root

- name: Install dynamic motd script
  template:
    src: update-motd.j2
    dest: /etc/update-motd.d/00-kittytel
    mode: '0755'
    owner: root
    group: root
  when: ansible_os_family == "Debian"

- name: clear out /etc/motd
  copy:
    content: ""
    dest: /etc/motd
    group: root
    owner: root
    mode: 0644
  when: ansible_os_family == "Debian"

- name: update bash PS1
  lineinfile:
    create: yes
    mode: 0755
    dest: /etc/bash.bashrc
    owner: root
    line: "PS1='${debian_chroot:+($debian_chroot)}\\[\\e[1;31m\\]\\u\\[\\e[1;33m\\]@\\[\\e[1;36m\\]\\h \\[\\e[1;33m\\]\\w \\[\\e[1;35m\\]\\$ \\[\\e[0m\\]'"
  when: ansible_os_family == "Debian"

- name: update bash PS1
  lineinfile:
    create: yes
    mode: 0755
    dest: /etc/bashrc
    owner: root
    line: "PS1='\\[\\e[1;31m\\]\\u\\[\\e[1;33m\\]@\\[\\e[1;36m\\]\\h \\[\\e[1;33m\\]\\w \\[\\e[1;35m\\]\\$ \\[\\e[0m\\]'"
  when: ansible_os_family == "RedHat"

- name: update bash PS1
  lineinfile:
    create: yes
    mode: 0755
    dest: /etc/skel/.bashrc
    owner: root
    line: "PS1='${debian_chroot:+($debian_chroot)}\\[\\e[1;31m\\]\\u\\[\\e[1;33m\\]@\\[\\e[1;36m\\]\\h \\[\\e[1;33m\\]\\w \\[\\e[1;35m\\]\\$ \\[\\e[0m\\]'"
  when: ansible_os_family == "Debian"
