---
- name: restart nginx
  service: 
    name: nginx 
    state: restarted 
    enabled: yes

- name: restart firewalld
  service: 
    name: firewalld 
    state: restarted 
    enabled: yes

- name: restart networking
  service:
    name: networking
    state: restarted
    enabled: yes
