---
- name: Add jetstack (cert-manager) helm chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
- name: Update helm repos
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_version: "{{ k3s_cert_manager_chart_version }}"
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values:
      dns01RecursiveNameserversOnly: true
      dns01RecursiveNameservers: "9.9.9.9:53,1.1.1.1:53"
      crds:
        enabled: true
    wait: true