---
- name: "Install dependencies for K3S"
  package:
    name:
    - nfs-utils
    state: present
  become: yes
- name: Check if k3s binary exists
  stat:
    path: /usr/local/bin/k3s
  register: k3s_stat
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  when: not k3s_stat.stat.exists
- name: Run k3s install script
  command: /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_KUBECONFIG_MODE: "644"
    INSTALL_K3S_EXEC: " server {{ k3s_setup_parameters }}"
  when: not k3s_stat.stat.exists
- name: Ensure KUBECONFIG is set in /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
    state: present
    create: yes
- name: Ensure .kube directory exists
  file:
    path: /root/.kube
    state: directory
- name: Copy k3s config to /root/.kube/config
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: true
