---
# Ansible tasks to deploy a PXE configuration and kickstart file for RHEL/friends
- name: "Include server-pxe-distro vars"
  include_vars: roles/server-pxe/vars/main.yml
- name: "Create Kickstart Template (Rocky Linux)"
  template:
    src: templates/deployment/rocky.ks.j2
    dest: /srv/tftp/ks/{{ vm_name }}.ks
    mode: 0644
  delegate_to: "pxe-{{ region_suffix }}.{{ vault_internal_host_dns }}"
  when: pxe_os == "rocky-stable"
- name: Create syslinux boot for MAC address (Rocky Linux EFI)
  template:
    src: templates/deployment/rocky-pxe.cfg.j2
    dest: /srv/tftp/bymac/mac-{{ sys_mac_addr | replace(":","-") | lower }}.ipxe
    mode: 0644
  delegate_to: "pxe-{{ region_suffix }}.{{ vault_internal_host_dns }}"
  when: pxe_os == "rocky-stable" and vm_use_efi 