---
# Ansible tasks to deploy Lets Encrypt for mx-lgb

- name: Deploy Lets Encrypt for dns-lgb.ad.kittytel.net
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: kittytel.net
    requested_letsencrypt_domain: kittytel.net
    requested_letsencrypt_san_list:
      - dns-lgb.ad.kittytel.net
