---

- name: Deploy Lets Encrypt for originull.org
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: originull.org
    requested_letsencrypt_domain: originull.org
    requested_letsencrypt_san_list:
      - www.originull.org
      - depot.originull.org

- name: Deploy Lets Encrypt for getgptassistant.com
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: getgptassistant.com
    requested_letsencrypt_domain: getgptassistant.com
    requested_letsencrypt_san_list:
      - www.getgptassistant.com