---
# Ansible tasks to deploy Lets Encrypt for svc-lgb

- name: Deploy Lets Encrypt for kittytel.net
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: kittytel.net
    requested_letsencrypt_domain: kittytel.net
    requested_letsencrypt_san_list:
      - www.kittytel.net
      - home.kittytel.net
      - portal.kittytel.net
      - monitor.kittytel.net

- name: Deploy Lets Encrypt for lbc.kittytel.net
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: kittytel.net
    requested_letsencrypt_domain: lbc.kittytel.net
    requested_letsencrypt_san_list:
      - lbc.kittytel.net

- name: Deploy Lets Encrypt for iquery.kittytel.net
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: kittytel.net
    requested_letsencrypt_domain: iquery.kittytel.net
    requested_letsencrypt_san_list:
      - iquery.kittytel.net

- name: "Deploy Lets Encrypt for {{ vault_private_domain }}"
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: "{{ vault_private_domain }}"
    requested_letsencrypt_domain: "{{ vault_private_domain }}"
    requested_letsencrypt_san_list:
      - "www.{{ vault_private_domain }}"

- name: Deploy Lets Encrypt for jacques.dog
  import_tasks: tasks/provisioning/letsencrypt.yml
  vars:
    requested_cloudflare_zone: jacques.dog
    requested_letsencrypt_domain: jacques.dog
    requested_letsencrypt_san_list: 
      - jacques.dog
      - www.jacques.dog