pxe_distro:
  - alpine
  - debian
  - fedora
  - gparted
  - rocky
  - opensuse
  - ubuntu
pxe_rocky_versions:
  - 10
  - 9
  - 8
pxe_debian_versions:
  - trixie
  - bookworm
  - bullseye
pxe_fedora_versions:
  - 43
  - 42
  - 41
  - 40
pxe_ubuntu_lts_versions:
  - 24.04
pxe_ubuntu_interim_versions:
  - "25.10"
  - "25.04"
pxe_opensuse_leap_versions:
  - 16.0
  - 15.6

debian_trixie_version: "13.1.0"
debian_bookworm_version: "12.12.0"
debian_bullseye_version: "11.11.0"
fedora_43_version: "1.6"
fedora_42_version: "1.1"
fedora_41_version: "1.4"
fedora_40_version: "1.14"
rocky_10_version: "10.0"
rocky_9_version: "9.5"
rocky_8_version: "8.10"

alpine_stable_version: "3.22.2"
ubuntu_lts_24.04_version: "24.04.3"
ubuntu_interim_version: "25.10"

gparted_live_version: "1.7.0-8"

# architecture variables
pxe_debian_arch:
  - amd64
  - arm64
pxe_linux_arch:
  - x86_64
  - aarch64
  
pxe_role_do_quick: false
#rocky_linux_mirror: http://dl.rockylinux.org/pub/rocky
ubuntu_linux_mirror: https://releases.ubuntu.com/
opensuse_mirror: https://download.opensuse.org
ipxe_version: "v1.21.1"
ipxe_use_signed_efi_amd64: false
pxeprov_enable_arm64: false
deploy_pxe_wds: false
pxe_server_hostname: netboot.local
pxe_http_ip: '{{ ansible_default_ipv4.address }}'

alpine_iso_url: "https://dl-cdn.alpinelinux.org/alpine/v{{ alpine_stable_version | regex_search('^([0-9]*\\.[0-9]*)') }}/releases/{{ desired_arch }}/alpine-{{ alpine_flavor }}-{{ alpine_stable_version }}-{{ desired_arch }}.iso"
alpine_netboot_url: "https://dl-cdn.alpinelinux.org/alpine/v{{ alpine_stable_version | regex_search('^([0-9]*\\.[0-9]*)') }}/releases/{{ desired_arch }}/alpine-netboot-{{ alpine_stable_version }}-{{ desired_arch }}.tar.gz"
debian_iso_url: "https://cdimage.debian.org/debian-cd/current/{{ desired_arch }}/iso-cd/debian-{{ debian_version }}-{{ desired_arch }}-netinst.iso"
debian_archive_iso_url: "https://cdimage.debian.org/mirror/cdimage/archive/{{ debian_version}}/{{ desired_arch }}/iso-cd/debian-{{ debian_version }}-{{ desired_arch }}-netinst.iso"
debian_netinst_url: "https://deb.debian.org/debian/dists/{{ debian_codename }}/main/installer-{{ desired_arch }}/current/images/netboot/netboot.tar.gz"
fedora_iso_url: "https://archives.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_version }}/Everything/{{ desired_arch }}/iso/Fedora-Everything-netinst-{{ desired_arch }}-{{ fedora_version }}-{{ fedora_release_version }}.iso"
fedora_archive_iso_url: "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/{{ fedora_version }}/Everything/{{ desired_arch }}/iso/Fedora-Everything-netinst-{{ desired_arch }}-{{ fedora_version }}-{{ fedora_release_version }}.iso"
rocky_iso_url: "https://dl.rockylinux.org/pub/rocky/{{ rocky_linux_version }}/isos/{{ desired_arch }}/Rocky-{{ rocky_linux_version }}-{{ desired_arch }}-minimal.iso"
rocky_vault_iso_url: "https://dl.rockylinux.org/vault/rocky/{{ rocky_linux_version }}/isos/{{ desired_arch }}/Rocky-{{ rocky_linux_version }}-{{ desired_arch }}-minimal.iso"
opensuse_leap_15_iso_url: "{{ opensuse_mirror }}/distribution/leap/{{ opensuse_leap_version }}/iso/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Build{{ opensuse_leap_build }}-Media.iso"
opensuse_leap_16_iso_url: "{{ opensuse_mirror }}/distribution/leap/{{ opensuse_leap_version }}/iso/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}.install.iso"
ubuntu_url: "{{ ubuntu_linux_mirror }}{{ ubuntu_version }}/ubuntu-{{ ubuntu_version }}-live-server-{{ desired_arch }}.iso"
ubuntu_url_alt: "https://cdimage.ubuntu.com/releases/{{ ubuntu_version | regex_search('^([0-9]*\\.[0-9]*)') }}/release/ubuntu-{{ ubuntu_version }}-live-server-{{ desired_arch }}.iso"
gparted_live_iso_url: "https://downloads.sourceforge.net/project/gparted/gparted-live-stable/{{ gparted_live_version }}/gparted-live-{{ gparted_live_version }}-amd64.iso"
