---
- name: pihole dns filtering resolver
  hosts: dns-lgb.ad.kittytel.net
  become: yes
  remote_user: "{{ vault_ansible_deployment_user }}"
  become_method: sudo
  # The following pre-task ansible check is
  # borrowed from Rocky Linux ansible playbooks
  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

    - name: Deploy failsafe user account
      import_tasks: tasks/provisioning/failsafe.yml
    - name: Deploy kitty telecom root CA
      import_tasks: tasks/provisioning/root-ca.yml
    - name: Update all apt packages to their latest version
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
    - name: Set Hostname
      hostname: 
        name: "{{ inventory_hostname }}"
    - name: "Deploy Lets Encrypt for {{ inventory_hostname }}"
      import_tasks: tasks/provisioning/letsencrypt.yml
      vars:
        requested_cloudflare_zone: kittytel.net
        requested_letsencrypt_domain: kittytel.net
        requested_letsencrypt_san_list:
          - "{{ inventory_hostname }}"

  roles:
    - monitoring-internal
    - shell-niceties
    - dns-filter
    - secure-ssh

  post_tasks:
    - name: Install cat's SSH keys
      import_tasks: tasks/provisioning/cat-ssh.yml
    - name: Ensure unbound is enabled and started
      service:
        name: unbound 
        state: restarted
        enabled: yes
    - name: Ensure pihole-FTL is enabled and started
      service:
        name: pihole-FTL 
        state: restarted
        enabled: yes
    - name: Ensure lighttpd is enabled and started
      service:
        name: lighttpd 
        state: restarted
        enabled: yes
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
