---
- name: Provision wordpress
  hosts: wordpress.kittytel.net
  become: yes
  remote_user: "{{ vault_ansible_deployment_user }}"
  become_method: sudo

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible
    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"
    - name: Set Hostname
      hostname: 
        name: "{{ inventory_hostname }}"
    - name: create user sysadm
      ansible.builtin.user:
        name: sysadm
        create_home: yes
    - name: add sysadm to sudo
      become: true
      copy:
        dest: /etc/sudoers.d/sysadm
        content: 'sysadm ALL=(ALL) NOPASSWD:ALL'

  tasks:
    - name: Install dependencies
      package: 
        name:
          - mariadb
          - nginx
          - php-fpm
          - php-mysqlnd
          - php-opcache
          - php-pecl-apcu
          - php-xml
          - python3-libsemanage
          - tar
          - unzip
          - wp-cli
        state: present
      when: ansible_os_family == "RedHat"
    - name: Deploy Lets Encrypt for wpdev.kittytel.net
      import_tasks: tasks/provisioning/letsencrypt.yml
      vars:
        requested_cloudflare_zone: kittytel.net
        requested_letsencrypt_domain: wpdev.kittytel.net
        requested_letsencrypt_san_list:
          - "chicago.wpdev.kittytel.net"
          - "la.wpdev.kittytel.net"
    - name: create user wpruntime
      ansible.builtin.user:
        name: wpruntime
        create_home: yes
        home: /var/www/wpruntime/
    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
    - name: Install nginx.conf
      template:
        src: wordpress/nginx.conf.j2
        dest: "/etc/nginx/nginx.conf"
        mode: '0644'
        owner: root
        group: root
    - name: Install nginx wpcommon.conf
      template:
        src: wordpress/nginx-wpcommon.conf.j2
        dest: "/etc/nginx/wpcommon.conf"
        mode: '0644'
        owner: root
        group: root
    - name: Install php.ini
      template:
        src: wordpress/php.ini.j2
        dest: "/etc/php.ini"
        mode: '0644'
        owner: root
        group: root
    - name: Install php-fpm.conf
      template:
        src: wordpress/php-fpm.conf.j2
        dest: "/etc/php-fpm.d/www.conf"
        mode: '0644'
        owner: root
        group: root
    - name: "Open port 443 in firewalld"
      firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
    - name: Check if wp-config.php exists
      stat:
        path: /var/www/wpruntime/wp-config.php
      register: wp_config_stat

    - name: Install and configure WordPress
      block:
        - name: download the latest WordPress zip file
          get_url:
            url: https://wordpress.org/latest.tar.gz
            dest: /tmp/wordpress.tar.gz
        - name: Extract WordPress
          unarchive:
            src: /tmp/wordpress.tar.gz
            dest: /var/www/wpruntime
            remote_src: yes
            extra_opts:
              - --strip-components=1
        - name: correct ownership
          file:
            path: /var/www/wpruntime
            owner: wpruntime
            group: wpruntime
            recurse: yes
            state: directory
        - name: cleanup downloaded zip
          file:
            path: /tmp/wordpress.tar.gz
            state: absent
        - name: Install nginx.conf
          template:
            src: wordpress/wp-config.php.j2
            dest: "/var/www/wpruntime/wp-config.php"
            mode: '0644'
            owner: root
            group: root
        - name: Install 404.html
          template:
            src: wordpress/404.html.j2
            dest: "/var/www/wpruntime/404.html"
            mode: '0644'
            owner: root
            group: root
        - name: Install 50x.html
          template:
            src: wordpress/50x.html.j2
            dest: "/var/www/wpruntime/50x.html"
            mode: '0644'
            owner: root
            group: root
        - name: "cleanup wordpress cruft {{ item }}"
          file:
            path: "/var/www/wpruntime/{{ item }}"
            state: absent
          with_items:
            - "readme.html"
            - "wp-config-sample.php"
            - "license.txt"
      when: not wp_config_stat.stat.exists
  post_tasks:
    - name: Ensure ~sysadm/.ssh exists
      become: yes
      file:
        path: /home/sysadm/.ssh
        state: directory
        owner: sysadm
        mode: 0700
    - name: Copy sysadm authorized_keys
      copy:
        src: files/cat_authorized_keys
        dest: /home/sysadm/.ssh/authorized_keys
        mode: '0600'
        owner: sysadm
    - name: ensure php-fpm is enabled
      service:
        name: php-fpm
        state: restarted
        enabled: yes
    - name: ensure nginx is enabled
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: ensure firewalld is enabled
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
