- name: Query DNS for A record of inventory_hostname
  set_fact:
    checkup_dns_query_result: "{{ lookup('community.general.dig', inventory_hostname) }}"
- name: "Create internal DNS record"
  block:
  - name: Query DHCP leases
    community.routeros.command:
      commands:
        - /ip/dhcp-server/lease/print detail where mac-address={{ sys_mac_addr|upper }}
    register: dhcp_result
    delegate_to: "{{ dhcp_server }}"
  - name: Extract IP from output
    set_fact:
      dhcp_ip: "{{ (dhcp_result.stdout_lines | join(' ') | regex_findall(' address=([0-9.]+)') | first ) | default('N/A', true) }}"
    delegate_to: "{{ dhcp_server }}"
  - name: "Set DNS A record"
    ansible.windows.win_dns_record:
      name: "{{ inventory_hostname.split('.')[0] }}"
      type: A
      zone: "{{ inventory_hostname.split('.')[1:] | join('.') }}"
      value: "{{ dhcp_ip }}"
      state: present
    delegate_to: "{{ internal_dns_controller }}"
    become: false
    when: "dhcp_ip != 'N/A'"
  when: checkup_dns_query_result == "NXDOMAIN" and sys_mac_addr is defined

