---
- name: Pre-Flight checks for KVM libvirt local hypervisor VM
  include_tasks: tasks/preflight/vm/libvirt-pre-vm-checks.yaml
  when: vm_hypervisor is defined
- name: Provision PXE for autoinstall
  include_role:
    name: pxe-autoinstall-client
  when: vm_hypervisor is defined and vm_exists is false
- name: Define VM
  include_tasks: tasks/preflight/vm/libvirt-define-vm.yaml
  when: vm_hypervisor is defined and vm_exists is false
- name: Cleanup PXE
  include_tasks: tasks/preflight/vm/pxe-cleanup.yaml
  when: vm_hypervisor is defined and vm_exists is false
- name: Pause 5 minutes for PXE autoinstallation
  pause:
    minutes: 5
  when: vm_hypervisor is defined and vm_exists is false
- name: Wait for SSH to respond (retry up to 30 times)
  wait_for:
    port: 22
    host: "{{ inventory_hostname }}"
    timeout: 5
  register: ssh_check
  retries: 30
  delay: 120
  until: ssh_check is succeeded
  when: vm_hypervisor is defined and vm_exists is false
