---
- name: Install packages for PXE Server Role
  package: 
    name: 
      - tftpd-hpa
      - nginx-light
      - samba
      - samba-vfs-modules
      - di-netboot-assistant
    state: present

- name: Copy nginx configuration
  template: 
    src: nginx.conf 
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    owner: root
    group: root

- name: Copy tftpd-hpa configuration
  template: 
    src: tftpd-hpa.default 
    dest: /etc/default/tftpd-hpa
    mode: '0644'
    owner: root
    group: root

- name: Create /srv/ks/ folder
  file:
    path: /srv/ks/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: "Setup Alpine Linux PXE"
  include_tasks: alpine-main.yaml
  when: '"alpine" in pxe_distro and pxe_role_do_quick == false'

- name: "Setup Debian GNU/Linux PXE"
  include_tasks: debian-main.yaml
  when: '"debian" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_debian_versions }}"
  loop_control:
    loop_var: debian_codename

- name: "Setup Rocky Linux PXE"
  include_tasks: rocky-main.yaml
  when: '"rocky" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_rocky_versions }}"
  loop_control:
    loop_var: rocky_version

- name: "Setup Fedora Linux PXE"
  include_tasks: fedora-main.yaml
  when: '"fedora" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_fedora_versions }}"
  loop_control:
    loop_var: fedora_version

- name: "Setup OpenSuSE Leap PXE"
  include_tasks: opensuse-leap.yaml
  when: '"opensuse" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_opensuse_leap_versions }}"
  loop_control:
    loop_var: opensuse_leap_version

- name: "Setup Ubuntu Linux LTS PXE"
  include_tasks: ubuntu-lts.yaml
  when: '"ubuntu" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_ubuntu_lts_versions }}"
  loop_control:
    loop_var: target_ubuntu_version

- name: "Setup Ubuntu Linux PXE"
  include_tasks: ubuntu-interim.yaml
  when: '"ubuntu" in pxe_distro and pxe_role_do_quick == false'
  loop: "{{ pxe_ubuntu_interim_versions }}"
  loop_control:
    loop_var: target_ubuntu_version

- name: "Setup Microsoft Windows"
  include_tasks: windows-main.yaml
  when: '"windows" in pxe_distro and pxe_role_do_quick == false'

- name: "Setup GParted Live"
  include_tasks: gparted-main.yaml
  when: '"gparted" in pxe_distro and pxe_role_do_quick == false'

- name: install iPXE
  include_tasks: ipxe.yaml

- name: Ensure nginx is running
  service:
    name: nginx 
    state: restarted
    enabled: yes

- name: Ensure samba is running
  service:
    name: smbd 
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Ensure samba is running
  service:
    name: smb
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Ensure tftpd-hpa is running
  service:
    name: tftpd-hpa 
    state: restarted
    enabled: yes
  notify:
    - restart tftpd-hpa