---
- name: Install packages for PXE Server Role
  package: 
    name: 
      - tftpd-hpa
      - nginx-light
      - samba
      - samba-vfs-modules
      - di-netboot-assistant
    state: present

- name: Copy nginx configuration
  template: 
    src: nginx.conf 
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
    owner: root
    group: root

- name: Copy tftpd-hpa configuration
  template: 
    src: tftpd-hpa.default 
    dest: /etc/default/tftpd-hpa
    mode: '0644'
    owner: root
    group: root

- name: Create /srv/ks/ folder
  file:
    path: /srv/ks/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: include_tasks for alpine
  include_tasks: alpine.yml
  when: '"alpine" in pxe_distro'
- name: "include_tasks for Debian Bullseye"
  include_tasks: debian.yml
  vars:
    debian_codename: bullseye
    debian_version: "{{ debian_bullseye_version }}"
  when: '"debian" in pxe_distro and "bullseye" in pxe_debian_versions'
- name: include_tasks for Debian Bookworm
  include_tasks: debian.yml
  vars:
    debian_codename: bookworm
    debian_version: "{{ debian_bookworm_version }}"
  when: '"debian" in pxe_distro and "bookworm" in pxe_debian_versions'
- name: "Include tasks for Rocky Linux 9"
  include_tasks: rocky.yml
  vars:
    rocky_linux_version: "{{ rocky_9_version }}"
  when: '"rocky" in pxe_distro and 9 in pxe_rocky_versions'
- name: "Include tasks for Rocky Linux 8"
  include_tasks: rocky.yml
  vars:
    rocky_linux_version: "{{ rocky_8_version }}"
  when: '"rocky" in pxe_distro and 8 in pxe_rocky_versions'
- name: include_tasks for fedora
  include_tasks: fedora.yml
  when: '"fedora" in pxe_distro'
- name: include_tasks for Ubuntu
  include_tasks: ubuntu.yml
  when: '"ubuntu" in pxe_distro'
- name: include_tasks for windows
  include_tasks: windows.yml
  when: '"windows" in pxe_distro'

- name: install iPXE
  include_tasks: ipxe.yml

- name: Ensure nginx is running
  service:
    name: nginx 
    state: restarted
    enabled: yes

- name: Ensure samba is running
  service:
    name: smbd 
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Ensure samba is running
  service:
    name: smb
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Ensure tftpd-hpa is running
  service:
    name: tftpd-hpa 
    state: restarted
    enabled: yes
  notify:
    - restart tftpd-hpa