---
# Playbook for OpenSUSE
- name: "Check OpenSuSE major version"
  set_fact:
    leap_major_version: "{{ opensuse_leap_version | string | split('.') | first | int }}"
- name: "Obtain Leap 15"
  block:
  - name: "Check if we have existing ISO"
    stat:
      path: "/srv/linux/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media.iso"
    register: iso_exists
  - name: "Retrieve OpenSUSE {{ opensuse_leap_version }} ISO"
    get_url: 
      url: '{{ opensuse_leap_15_iso_url }}'
      dest: "/srv/linux/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media.iso"
    when: "not iso_exists.stat.exists"
  - name: "Create folder for openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media ISO mount"
    file:
      path: "/srv/distro/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media/"
      state: directory
      mode: '0755'
      owner: root
      group: root
    ignore_errors: true
  - name: "Mount OpenSUSE {{ opensuse_leap_version }} ISO"
    mount:
      path: "/srv/distro/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media/"
      src: "/srv/linux/openSUSE-Leap-{{ opensuse_leap_version }}-NET-{{ desired_arch }}-Media.iso"
      fstype: iso9660
      opts: ro,loop,nofail
      state: mounted
  when: leap_major_version | int <= 15
- name: "Obtain Leap 16"
  block:
  - name: "Check if we have existing ISO"
    stat:
      path: "/srv/linux/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}.install.iso"
    register: iso_exists
  - name: "Retrieve OpenSUSE {{ opensuse_leap_version }} ISO"
    get_url: 
      url: '{{ opensuse_leap_16_iso_url }}'
      dest: "/srv/linux/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}.install.iso"
    when: "not iso_exists.stat.exists"
  - name: "Create folder for Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }} ISO mount"
    file:
      path: "/srv/distro/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}/"
      state: directory
      mode: '0755'
      owner: root
      group: root
    ignore_errors: true
  - name: "Mount OpenSUSE {{ opensuse_leap_version }} ISO"
    mount:
      path: "/srv/distro/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}/"
      src: "/srv/linux/Leap-{{ opensuse_leap_version }}-online-installer-{{ desired_arch }}.install.iso"
      fstype: iso9660
      opts: ro,loop,nofail
      state: mounted
  when: leap_major_version | int >= 16