---
# Playbook for Ubuntu LTS

- name: "Check if we have existing ISO"
  stat:
    path: "/srv/linux/ubuntu-{{ ubuntu_lts_version }}-netboot-{{ desired_arch }}.iso"
  register: iso_exists
  vars:
    desired_arch: amd64

- name: Retrieve Ubuntu netboot Linux {{ ubuntu_lts_version }} ISO
  get_url: 
    url: '{{ ubuntu_lts_url }}'
    dest: "/srv/linux/ubuntu-{{ ubuntu_lts_version }}-netboot-{{ desired_arch }}.iso"
  vars:
    desired_arch: amd64
  when: "not iso_exists.stat.exists"

- name: Mount Ubuntu netboot {{ ubuntu_lts_version }} ISO
  mount:
    path: "/srv/distro/ubuntu-{{ ubuntu_lts_version }}-netboot-{{ desired_arch }}/"
    src: "/srv/linux/ubuntu-{{ ubuntu_lts_version }}-netboot-{{ desired_arch }}.iso"
    fstype: iso9660
    opts: ro,loop
    state: mounted
  vars:
    desired_arch: amd64
