---
# Ansible tasks to deploy a PXE configuration and kickstart file for RHEL/friends

- name: "Create Kickstart Template (Rocky Linux 9)"
  template:
    src: rocky.ks.j2
    dest: /srv/tftp/ks/{{ inventory_hostname }}.ks
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  vars:
    rocky_linux_version: "{{ rocky_9_version }}"
  when: "pxe_os == 'rocky' and deploy_rocky_version == 9"

- name: "Create Kickstart Template (Rocky Linux 8)"
  template:
    src: rocky-8.ks.j2
    dest: /srv/tftp/ks/{{ inventory_hostname }}.ks
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: "pxe_os == 'rocky' and deploy_rocky_version == 8"

- name: "Create Kickstart Template (Fedora)"
  template:
    src: fedora.ks.j2
    dest: /srv/tftp/ks/{{ inventory_hostname }}.ks
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: "pxe_os == 'fedora'"

- name: Create iPXE boot for MAC address
  template:
    src: rocky-pxe.cfg.j2
    dest: /srv/tftp/bymac/mac-{{ sys_mac_addr | replace(":","-") | lower }}.ipxe
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"