---
# Ansible tasks to deploy a PXE configuration and kickstart file for RHEL/friends

- name: "Create Kickstart Template"
  template:
    src: kickstart.ks.j2
    dest: /srv/tftp/ks/{{ inventory_hostname }}.ks
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: "system_os == 'rocky' or system_os == 'rhel' or system_os == 'almalinux' or system_os == 'fedora'"

- name: Create iPXE boot for MAC address
  template:
    src: rocky-pxe.cfg.j2
    dest: /srv/tftp/bymac/mac-{{ sys_mac_addr | replace(":","-") | lower }}.ipxe
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"