---
# Ansible tasks to deploy a PXE configuration and unattend.xml file for Windows
- name: "Create winselect.ini Template"
  template:
    src: winselect.ini.j2
    dest: /srv/tftp/ks/{{ sys_mac_addr | replace(":","-") | upper }}.ini
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: system_os == "windows" 
- name: "Create Windows Server unattend.xml Template"
  template:
    src: server-unattend.xml.j2
    dest: /srv/tftp/ks/{{ sys_mac_addr | replace(":","-") | upper }}.xml
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: system_os == "windows" and deploy_windows_version in win_deploy_server_versions
- name: "Create Windows LTSC unattend.xml Template"
  template:
    src: ltsc-unattend.xml.j2
    dest: /srv/tftp/ks/{{ sys_mac_addr | replace(":","-") | upper }}.xml
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: system_os == "windows" and deploy_windows_version in win_deploy_ltsc_versions
  
- name: Create iPXE boot for MAC address (WinPE)
  template:
    src: windows-pxe.cfg.j2
    dest: /srv/tftp/bymac/mac-{{ sys_mac_addr | replace(":","-") | lower }}.ipxe
    mode: 0644
  delegate_to: "{{ pxe_server_delegation }}"
  when: system_os == "windows" 