---
- name: Install ArgoCD
  block:
  - name: Add ArgoCD helm chart repo
    kubernetes.core.helm_repository:
      name: argo-cd
      repo_url: "https://argoproj.github.io/argo-helm"
  - name: Update helm repos
    kubernetes.core.helm:
      name: dummy
      namespace: kube-system
      state: absent
      update_repo_cache: true
  - name: Deploy argo-cd
    kubernetes.core.helm:
      name: argo-cd
      chart_version: "{{ k3s_argo_cd_chart_version }}"
      chart_ref: argo-cd/argo-cd
      release_namespace: argo-cd
      create_namespace: true
      values:
        global:
          domain: "{{ argocd_ingress_host }}"
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-dns"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/service-upstream: "true"
            hosts:
              - "{{ argocd_ingress_host }}"
            tls: true
      wait: true
  - name: "Update ArgoCD admin password"
    kubernetes.core.k8s:
      api_version: v1
      kind: Secret
      name: argocd-secret
      namespace: argo-cd
      state: present
      merge_type: strategic-merge
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: argocd-secret
          namespace: argo-cd
        stringData:
          admin.password: "{{ argocd_admin_password | password_hash('bcrypt') }}"
          admin.passwordMtime: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime() }}"
    no_log: true
  when: inventory_hostname in groups['k8s_main_node']|default([])
