---
- name: Create CloudFlare API secret token
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
        namespace: kube-system
      type: Opaque
      stringData:
        api-token: "{{ vault_cloudflare_dns_api_token }}"
- name: Create the ClusterIssuer letsencrypt-dns
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-dns
        namespace: kube-system
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: "{{ vault_cloudflare_api_email }}"
          privateKeySecretRef:
            name: letsencrypt-dns-key
          solvers:
          - dns01:
              cloudflare:
                email: "{{ vault_cloudflare_api_email }}"
                apiTokenSecretRef:
                  name: cloudflare-api-token-secret
                  key: api-token