---
- name: Create default wildcard ingress certificate
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        api-token: "{{ vault_cloudflare_dns_api_token }}"
  when: inventory_hostname in groups['k8s_main_node']|default([])
- name: Create default wildcard ingress certificate
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-dns
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: "{{ vault_cloudflare_api_email }}"
          privateKeySecretRef:
            name: letsencrypt-dns-key
          solvers:
          - dns01:
              cloudflare:
                email: "{{ vault_cloudflare_api_email }}"
                apiTokenSecretRef:
                  name: cloudflare-api-token-secret
                  key: api-token
  when: inventory_hostname in groups['k8s_main_node']|default([])
