---
- name: Install MetalLB
  block:
  - name: Add MetalLB helm chart repo
    kubernetes.core.helm_repository:
      name: metallb
      repo_url: "https://metallb.github.io/metallb"
  - name: Update helm repos
    kubernetes.core.helm:
      name: dummy
      namespace: kube-system
      state: absent
      update_repo_cache: true
  - name: Deploy MetalLB
    kubernetes.core.helm:
      name: metallb
      chart_version: "{{ k3s_metallb_chart_version }}"
      chart_ref: metallb/metallb
      release_namespace: kube-system
      wait: true
  - name: Create default wildcard ingress certificate
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default-address-pool
          namespace: kube-system
        spec:
          addresses:
          - "{{ metallb_ip_range_start }}-{{ metallb_ip_range_end }}"
  - name: Create default wildcard ingress certificate
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: l2adv
          namespace: kube-system
  when: inventory_hostname in groups['k8s_main_node']|default([])
